name: flutter_ecomm_app
description: "A Flutter e-commerce application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

#------ PACKAGES ------S#

dependencies:
  flutter:
    sdk: flutter

  #Icons

  cupertino_icons: ^1.0.8

  #Flutter Packages
  get: ^4.7.3
  http: ^1.6.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  logger: ^2.6.2
  get_storage: ^2.1.1

  #Product specific

# ------ Packages End -------- #

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ------------  LOCAL ASSETS ----------- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
  # ------------  LOCAL FONTS  ----------- #

  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\Poppins-LightItalic.ttf
          weight: 300
        - asset: assets\fonts\Poppins-Regular.ttf
          weight: 400
        - asset: assets\fonts\Poppins-Italic.ttf
          style: italic
        - asset: assets\fonts\Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets\fonts\Poppins-Medium.ttf
          weight: 500
        - asset: assets\fonts\Poppins-SemiBold.ttf
          weight: 600
        - asset: assets\fonts\Poppins-Bold.ttf
          weight: 800
